version: v1
metadata:
  name: Blur
  description: Shift
  author: tympanus
  source: https://tympanus.net/Development/AmbientCanvasBackgrounds/index3.html
parameters:
  - id: opacity
    default: "0.5"
helpers:
  insert_baseurl: true
template: >
  <!doctype html>

  <html lang="en" class="no-js">
    <head>
      <meta charset="UTF-8" />
      <meta name="author" content="Codrops" />
      <style>
        article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block;}audio,canvas,video{display:inline-block;}audio:not([controls]){display:none;height:0;}[hidden]{display:none;}html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;}body{margin:0;}a:focus{outline:thin dotted;}a:active,a:hover{outline:0;}h1{font-size:2em;margin:0.67em 0;}abbr[title]{border-bottom:1px dotted;}b,strong{font-weight:bold;}dfn{font-style:italic;}hr{-moz-box-sizing:content-box;box-sizing:content-box;height:0;}mark{background:#ff0;color:#000;}code,kbd,pre,samp{font-family:monospace,serif;font-size:1em;}pre{white-space:pre-wrap;}q{quotes:"\201C" "\201D" "\2018" "\2019";}small{font-size:80%;}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline;}sup{top:-0.5em;}sub{bottom:-0.25em;}img{border:0;}svg:not(:root){overflow:hidden;}figure{margin:0;}fieldset{border:1px solid #c0c0c0;margin:0 2px;padding:0.35em 0.625em 0.75em;}legend{border:0;padding:0;}button,input,select,textarea{font-family:inherit;font-size:100%;margin:0;}button,input{line-height:normal;}button,select{text-transform:none;}button,html input[type="button"],input[type="reset"],input[type="submit"]{-webkit-appearance:button;cursor:pointer;}button[disabled],html input[disabled]{cursor:default;}input[type="checkbox"],input[type="radio"]{box-sizing:border-box;padding:0;}input[type="search"]{-webkit-appearance:textfield;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;box-sizing:content-box;}input[type="search"]::-webkit-search-cancel-button,input[type="search"]::-webkit-search-decoration{-webkit-appearance:none;}button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0;}textarea{overflow:auto;vertical-align:top;}table{border-collapse:collapse;border-spacing:0;}
        *,
        *::after,
        *::before {
            box-sizing: border-box;
        }

            body {
                font-family: Didot, "Didot LT STD", "Bodoni MT", "ltc-bodoni-175", "Hoefler Text", Garamond, "Times New Roman", serif;
                min-height: 100vh;
                color: #57585c;
                color: var(--color-text);
                background-color: #000;
                opacity:{{parameter: opacity}};
                overflow: hidden;
            }
        p {
        margin-bottom: 10px;
        font-size: 18px;
        line-height: 140%;
        }

        .canvas {
        position: relative;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        overflow: hidden;
        width: 100%;
        height: 100vh;
        -webkit-box-pack: center;
        -webkit-justify-content: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        background-color: #242424;
        color: #fff;
        }

        .blur-overlay {
        position: absolute;
        left: 0%;
        top: 0%;
        right: 0%;
        bottom: 0%;
        z-index: 1;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        width: 100%;
        height: 100%;
        -webkit-box-pack: center;
        -webkit-justify-content: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-backdrop-filter: brightness(280%) saturate(130%) blur(80px);
        backdrop-filter: brightness(280%) saturate(130%) blur(80px);
        }

        .heading {
        margin-top: 0px;
        margin-bottom: 0px;
        color: hsla(0, 0%, 100%, 0.75);
        font-size: 6vw;
        line-height: 100%;
        text-align: center;
        text-transform: uppercase;
        }

        .utility-page-wrap {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        width: 100vw;
        height: 100vh;
        max-height: 100%;
        max-width: 100%;
        -webkit-box-pack: center;
        -webkit-justify-content: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        }

        .utility-page-content {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        width: 260px;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
        text-align: center;
        }

        .utility-page-form {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
        -webkit-box-align: stretch;
        -webkit-align-items: stretch;
        -ms-flex-align: stretch;
        align-items: stretch;
        }

        .og-source {
        position: relative;
        left: auto;
        top: auto;
        right: auto;
        bottom: 20px;
        z-index: 4;
        display: block;
        color: #000;
        text-align: center;
        }

        .section {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        padding-top: 150px;
        padding-bottom: 150px;
        -webkit-box-pack: center;
        -webkit-justify-content: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        }

        .content {
        max-width: 420px;
        margin: 40px;
        }

        .image {
        width: 45%;
        max-width: 450px;
        margin: 40px;
        }

        .heading-2 {
        margin-top: 0px;
        margin-bottom: 20px;
        }

        .wrapper {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: justify;
        -webkit-justify-content: space-between;
        -ms-flex-pack: justify;
        justify-content: space-between;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        }

        .adjust-panel {
        position: fixed;
        left: auto;
        top: auto;
        right: 10px;
        bottom: 10px;
        z-index: 4;
        width: 300px;
        padding-right: 20px;
        padding-bottom: 30px;
        padding-left: 20px;
        border-radius: 6px;
        background-color: hsla(0, 0%, 100%, 0.4);
        -webkit-backdrop-filter: blur(20px);
        backdrop-filter: blur(20px);
        color: #000;
        }

        .slider-wrapper {
        margin-bottom: 10px;
        }

        .range-wrapper {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        height: 40px;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        }

        .head {
        margin-top: 40px;
        margin-bottom: 20px;
        }

        .button {
        margin-top: 20px;
        padding: 10px 25px;
        border-radius: 20px;
        background-color: #000;
        }

        .scroll-down {
        position: absolute;
        left: 0%;
        top: auto;
        right: 0%;
        bottom: 20px;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        max-width: 200px;
        margin-right: auto;
        margin-left: auto;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
        -webkit-box-pack: center;
        -webkit-justify-content: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        color: #fff;
        text-decoration: none;
        cursor: pointer;
        }

        @media screen and (max-width: 767px) {
        .section {
            -webkit-box-orient: vertical;
            -webkit-box-direction: normal;
            -webkit-flex-direction: column;
            -ms-flex-direction: column;
            flex-direction: column;
        }
        .image {
            width: 80%;
            margin-top: 0px;
        }
        }
      </style>
    </head>
    <body>
      <div class="canvas">
        <div class="blur-overlay"></div>
        <script src="noise.min.js"></script>
        <script src="shift.js"></script>
      </div>
    </body>
  </html>
