name: Generate Image Previews and Deploy to Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate Package Metadata"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Dependencies in helpers
        run: npm install
        working-directory: ./helpers
    
      - name: Generate Metadata
        run: node ./helpers/create-metadata.js

      - name: Copy web preview to root
        run: |
          echo "Copying web preview app to root..."
          cp docs/web-preview/index.html ./index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload initial artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          name: "initial-artifact-${{ github.run_id }}"  

      - name: Deploy to GitHub Pages
        id: deployment-initialize
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "initial-artifact-${{ github.run_id }}" 

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./helpers

      - name: Generate Image Metadata
        run: node ./helpers/create-imagepreview.js

      - name: Delete node_modules
        run: |
          echo "Deleting all node_modules folders..."
          find . -name "node_modules" -type d -prune -exec rm -rf {} +

      - name: Delete docs
        run: |
          echo "Deleting all docs folders..."
          find . -name "docs" -type d -prune -exec rm -rf {} +

      - name: Delete schema
        run: |
          echo "Deleting all schema folders..."
          find . -name "schema" -type d -prune -exec rm -rf {} +

      - name: Delete helpers
        run: |
          echo "Deleting all helpers folders..."
          find . -name "helpers" -type d -prune -exec rm -rf {} +

      - name: Delete dist
        run: |
          echo "Deleting all dist folders..."
          find . -name "dist" -type d -prune -exec rm -rf {} +

      - name: Upload updated artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          name: "updated-artifact-${{ github.run_id }}"  

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "updated-artifact-${{ github.run_id }}" 
